### ISSUE TITLE
how do you run this ?

### ISSUE THREAD

**Issue by oscie57** [xzn/ntrviewer-hr#1]
trying to run `ntrviewer.exe` just does nothing, and there doesnt seem to be a way to input an IP either. i tried reading the code, and couldnt find anything in there.

**Comment by xzn** [comment]
Sorry I re-uploaded the file, was missing a few libraries (SDL2 and ANGLE).

The UI should look like this:

![image](https://github.com/xzn/ntrviewer-hr/assets/1617680/147c2733-bb64-4dfe-b349-ef8b29447de0)

Cheers!
