### ISSUE TITLE
how i fix timeout?

### ISSUE THREAD

**Issue by mottyan1991** [xzn/ntrviewer-hr#5]
main.c::tcp_connect connecting to 192.168.40.120:8000 ...
main.c::udp_recv_thread_func port bound at 192.168.40.163:8000
main.c::tcp_connect connection timeout
how i fix that errors?
tcp?

**Comment by xzn** [comment]
The error means the viewer is unable to establish TCP connection to the 3DS.

Some guesses at possible fix:
Make sure NTR is running before trying to connect.
Check your firewall and make sure the viewer is allowed connections.
Make sure the IP addresses are correct.

Let me know the steps you take to run the programs (both on PC and on 3DS) if you can't fix the errors.

Thanks.

**Comment by mottyan1991** [comment]
thankyou xzn. I write my taked steps
1 : launch bootntr ,  (so i returned home)
2 : run ntrviewer.exe.
3 : write ip and connect.
i taked steps and error.
(im japanese so English may be wrong)

**Comment by mottyan1991** [comment]
/ps/
I have old 3ds

**Comment by mottyan1991** [comment]
yeah its fixed that. but remoteplay only new3ds😓
