### ISSUE TITLE
rtRecvSocket failed: ffffffff 

### ISSUE THREAD

**Issue by TropicalCyclone** [xzn/ntrviewer-hr#7]
my NTR viewer is just blank with blue background, FPS 000 in the top bar.

I followed all the tutorials on how to make this work, just blank. It looks like its connected but theres no video.

"
main.c:4370:SDL_main ogl version string: 4.6.0 NVIDIA 566.03
main.c:4386:SDL_main ogl version: 4.6
main.c:4168:udp_recv_thread_func port bound at 192.168.0.26:8001
main.c:570:tcp_connect connecting to 192.168.0.34:8000 ...
main.c:594:tcp_connect connected
[239.636858][f]source/ns.c:415:nsMainLoop rtRecvSocket failed: ffffffff
[239.711006][1a]source/ns.c:415:nsMainLoop rtRecvSocket failed: ffffffff
[32475.097479][f]source/menu/rp_menu.c:640:rpStartupFromMenu Remote play already started, updating params.
"

**Comment by xzn** [comment]
That is strange. Just to confirm, the UI is showing, but there's no video when you hit connect? Is your firewall allowing UDP connections to go through from 3DS to PC?

**Comment by TropicalCyclone** [comment]
I tried normal NTR with snickerstream and it works, its just this version thats broken

**Comment by TropicalCyclone** [comment]
I think allowing the app itself through firewall is the solution! Thanks!
